os:
  - osx

env:
  global:
    - XCODE_XCCONFIG_FILE=$TRAVIS_BUILD_DIR/.travis.xcconfig

install:
  - wget https://www.fusetools.com/downloads/0.25.1.7615/osx -O fuse-installer.pkg
  - sudo installer -pkg fuse-installer.pkg -target /

script:
  - uno build NativeControls/NativeControls.unoproj
  - uno build -tios Example/Example.unoproj
